import {
  Activity,
  Package,
  Thermometer,
  MapPin,
  User,
  ShieldCheck,
  Database,
} from "lucide-react";

const iconMap = {
  SHIPMENT_CREATED: Package,
  SHIPMENT_UPDATED: Package,
  SENSOR_DATA: Thermometer,
  LOCATION_UPDATED: MapPin,
  USER_LOGIN: User,
  SECURITY_EVENT: ShieldCheck,
  SYSTEM_EVENT: Database,
};

export default function AuditTimeline({
  events = [],
  onEventClick,
}) {
  if (!events.length) {
    return (
      <div className="audit-empty">
        <Database size={42} />

        <h3>No audit events found</h3>

        <p>
          Events generated by the system will appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="audit-timeline">
      {events.map((event, index) => {
        const Icon =
          iconMap[event.type] || Activity;

        const date = event.createdAt
          ? new Date(event.createdAt)
          : new Date();

        return (
          <div
            className="audit-timeline-item"
            key={event._id || event.id || index}
          >
            {/* Timeline line */}
            {index !== events.length - 1 && (
              <div className="timeline-line" />
            )}

            {/* Event icon */}
            <div
              className={`audit-event-icon ${
                getEventClass(event.type)
              }`}
            >
              <Icon size={18} />
            </div>

            {/* Event content */}
            <button
              className="audit-event-content"
              onClick={() => onEventClick?.(event)}
            >
              <div className="audit-event-header">
                <div>
                  <h3>
                    {formatEventType(
                      event.type || event.action
                    )}
                  </h3>

                  <span className="audit-event-time">
                    {date.toLocaleString()}
                  </span>
                </div>

                <span
                  className={`audit-event-badge ${
                    getEventClass(event.type)
                  }`}
                >
                  {event.type || "EVENT"}
                </span>
              </div>

              <p>
                {event.message ||
                  event.description ||
                  "System event recorded."}
              </p>

              <div className="audit-event-meta">
                {event.shipmentId && (
                  <span>
                    Shipment:{" "}
                    <strong>
                      {event.shipmentId}
                    </strong>
                  </span>
                )}

                {event.user && (
                  <span>
                    User:{" "}
                    <strong>
                      {event.user}
                    </strong>
                  </span>
                )}

                {event.temperature !== undefined && (
                  <span>
                    Temperature:{" "}
                    <strong>
                      {event.temperature}°C
                    </strong>
                  </span>
                )}
              </div>
            </button>
          </div>
        );
      })}
    </div>
  );
}

function formatEventType(type = "SYSTEM_EVENT") {
  return type
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}

function getEventClass(type = "") {
  const value = type.toLowerCase();

  if (value.includes("sensor")) {
    return "sensor";
  }

  if (value.includes("security")) {
    return "security";
  }

  if (value.includes("location")) {
    return "location";
  }

  if (value.includes("created")) {
    return "created";
  }

  if (value.includes("updated")) {
    return "updated";
  }

  if (value.includes("login")) {
    return "login";
  }

  return "default";
}